name: linux
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build_Linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Compile Drizzle2D
      run: make
