name: MSBuild
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest
    steps:    
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Printq
      run: dir "C:\Program Files (x86)\MSBuild\"
    
    - name: Install Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      with:
        vulkan-query-version: 1.3.204.0
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: true
    
    - name: Install GLFW
      run: |
        powershell -c "Invoke-WebRequest -Uri 'https://github.com/glfw/glfw/releases/download/3.3.8/glfw-3.3.8.bin.WIN64.zip' -OutFile glfw.zip"
        powershell.exe -NoP -NonI -Command "Expand-Archive '.\glfw.zip' 'C:\Program Files\GLFW'"
        dir "C:\Program Files\GLFW\glfw-3.3.8.bin.WIN64"
    
    - name: Download STB
      run: |
        git clone --depth=1 https://github.com/nothings/stb.git
    
    - name: Download GLM
      run: |
        git clone --depth=1 https://github.com/g-truc/glm.git
    
    - name: Install Visual Studio 2022 Community
      shell: cmd
      run: |
        powershell -c "Invoke-WebRequest -Uri 'https://download.visualstudio.microsoft.com/download/pr/7ac7457f-ba6e-4a12-ba2c-1adebad20070/956d3034e261ad0645371d0ffb21ab5bd3c85ed81feffd11171606fc2bc173ff/vs_Community.exe' -OutFile vs_Community.exe"
        vs_Community.exe --installPath "C:\Program Files\Microsoft Visual Studio\2022\Community" --add Microsoft.VisualStudio.Workload.NativeDesktop --includeRecommended --quiet --wait
    
    - name: Download Windows SDK
      shell: powershell
      run: |
        Invoke-WebRequest -Uri "https://download.microsoft.com/download/7/9/6/7962e9ce-cd69-4574-978c-1202654bd729/windowssdk/winsdksetup.exe" -OutFile winsdksetup.exe
        mkdir C:/Win10SDK
    
    - name: Install Windows SDK
      shell: cmd
      run: winsdksetup.exe /features + /quiet /norestart
    
    - name: Download MESA
      run: git clone https://github.com/Mesa3D/mesa.git
    
    - name: Build
      shell: cmd
      run: |
        dir "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\"
        "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\Hostx64\x64\cl.exe" /EHsc /I. /Imesa\include /I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\km" /I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\winrt" /I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\shared" /I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\cppwinrt" /I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um" /I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.20348.0\ucrt" /I"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include" /I"C:\Program Files\GLFW\include" /I"D:\a\Drizzle2D\Drizzle2D\VULKAN_SDK\include" /Iglm /Istb -std:c++20 *.cpp /NODEFAULTLIB:library "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\ucrt\x64\libucrt.lib" "C:\Program Files\GLFW\lib\glfw3.lib" "D:\a\Drizzle2D\Drizzle2D\VULKAN_SDK\lib\vulkan-1.lib" "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64\kernel32.lib" "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64\user32.lib" "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64\gdi32.lib" "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64\winspool.lib" "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64\comdlg32.lib" "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64\advapi32.lib" "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64\shell32.lib" "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64\ole32.lib" "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64\oleaut32.lib" "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64\uuid.lib" "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64\odbc32.lib" "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64\odbccp32.lib" /link /LIBPATH:"D:\a\Drizzle2D\Drizzle2D\VULKAN_SDK\lib" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\ucrt\x64" /LIBPATH:"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\lib\onecore\x64" /LIBPATH:"C:\Program Files\GLFW\lib" /Fe:main.exe
