name: MSBuild
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
permissions:
  contents: read
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Setup Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      
    - name: Install GLFW
      run: |
        git clone https://github.com/glfw/glfw.git
        cd glfw
        cmake -S . -B build -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF
        cmake --build build --config Release
        cmake --install build --prefix $(ProgramFiles)\GLFW
        
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:VULKAN_SDK_PATH="${{env.VK_SDK_PATH}}" /p:GLFW_PATH="$(ProgramFiles)\GLFW" ${{env.SOLUTION_FILE_PATH}}
