name: Push to Visual Studio App Center

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Install Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      with:
        vulkan-query-version: 1.3.204.0
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: true

      # Cache STB, GLM, and MESA repositories
    - name: Cache STB, GLM, MESA,  GLFW
      id: cache-deps
      uses: actions/cache@v2
      with:
          path: |
            stb
            glm
            mesa
            GLFW
          key: ${{ runner.os }}-deps-${{ hashFiles('**/dependencies-lock.json') }}
          restore-keys: ${{ runner.os }}-deps-
    
    - name: Install GLFW
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
          powershell -c "Invoke-WebRequest -Uri 'https://github.com/Cherrytree56567/Drizzle2D/raw/main/GLFW.zip' -OutFile glfw.zip"
          powershell.exe -NoP -NonI -Command "Expand-Archive '.\glfw.zip' ${{ github.workspace }}"
          dir ${{ github.workspace }}\\GLFW

    - name: Download STB
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
          git clone --depth=1 https://github.com/nothings/stb.git

    - name: Download GLM
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
          git clone --depth=1 https://github.com/g-truc/glm.git

    - name: Download MESA
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: git clone https://github.com/Mesa3D/mesa.git
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        msbuild.exe /m Drizzle2DVulkan.vcxproj /p:Configuration=Release -t:restore -p:RestorePackagesConfig=true /p:OutputPath=${{env.GITHUB_WORKSPACE}}
    
    - name: Create Zip Archive using 7-Zip
      run: |
        "C:\Program Files\7-Zip\7z.exe" a output.zip ${{env.GITHUB_WORKSPACE}}
    
    - name: upload artefact to App Center
      uses: wzieba/AppCenter-Github-Action@v1
      with:
        appName: wzieba/Sample-App
        token: ${{secrets.APP_CENTER_TOKEN}}
        group: Testers
        file: output.zip
        notifyTesters: true
        debug: false
